---
- name: Update the APT repository
  apt: update_cache=yes
  become: yes
  become_method: sudo
  become_user: root
  tags:
    - needs_internet_connection

- name: Upgrade the packages
  apt: upgrade=full
  become: yes
  become_method: sudo
  become_user: root
  tags:
    - needs_internet_connection
